name: cron

on:
  schedule:
    # https://crontab.guru/
    - cron: '0,16,30 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.5"
      - run: pip install -r requirements.txt
      - run: python main.py --token="${{ secrets.SLACK_BOT_TOKEN }}"
